In [30]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [31]:
data = pd.read_csv('file1.csv')

In [32]:
describe = open("desc1.txt")
describe = describe.read()
print(describe)

Body measurements of 446 physically active individuals.

Description
Body girth measurements and skeletal diameter measurements, as well as age, weight and gender, are given for 446 physically active individuals - 223 men and 223 women.

Format
A data frame with 446 observations on the following 18 variables.

attr1
A numerical vector, respondent's biacromial diameter in centimeters.

attr2
A numerical vector, respondent's biiliac diameter (pelvic breadth) in centimeters.

attr3
A numerical vector, respondent's bitrochanteric diameter in centimeters.

attr4
A numerical vector, respondent's elbow diameter in centimeters, measured as sum of two elbows.

attr5
A numerical vector, respondent's wrist diameter in centimeters, measured as sum of two wrists.

attr6
A numerical vector, respondent's knee diameter in centimeters, measured as sum of two knees.

attr7
A numerical vector, respondent's ankle diameter in centimeters, measured as sum of two ankles.

attr8
A numerical vector, respondent's shoulder girth in centimeters, measured over deltoid muscles.

attr9
A numerical vector, respondent's waist girth in centimeters, measured at the narrowest part of torso below the rib cage as average of contracted and relaxed position.

attr10
A numerical vector, respondent's bicep girth in centimeters, measured when flexed as the average of right and left girths.

attr11
A numerical vector, respondent's forearm girth in centimeters, measured when extended, palm up as the average of right and left girths.

attr12
A numerical vector, respondent's knee girth in centimeters, measured as sum of two knees.

attr13
A numerical vector, respondent's calf maximum girth in centimeters, measured as average of right and left girths.

attr14
A numerical vector, respondent's ankle minimum girth in centimeters, measured as average of right and left girths.

attr15
A numerical vector, respondent's wrist minimum girth in centimeters, measured as average of right and left girths.

attr16
A numerical vector, respondent's age in years.

attr17
A categorical vector, 1 if the respondent is male, 0 if female.

attr18
A numerical vector, respondent's weight in kilograms.

In [33]:
data.rename(
    columns={"attr1": "biacromial diameter", "attr2": "biiliac diameter", "attr3": "bitrochanteric diameter",
    "attr4" :"elbow diameter","attr5" : "wrist diameter", "attr6" : "knee diameter", "attr7":"ankle diameter",
    "atr8" : "shoulder girth", "attr9": "waist girth","attr10":"bicep girth","attr11": "forearm girth",
    "attr12":"knee girth", "attr13":"calf maximum girth","attr14":"ankle minimum girth","attr15":"wrist_min_girth",
    "attr16":"age", "attr17":"sex","attr18":"weight"},
    inplace=True,
)

In [34]:
data.head()

,biacromial diameter,biiliac diameter,bitrochanteric diameter,elbow diameter,wrist diameter,knee diameter,ankle diameter,shoulder girth,waist girth,bicep girth,forearm girth,knee girth,calf maximum girth,ankle minimum girth,wrist_min_girth,age,sex,weight
0,42.9,26.0,31.5,13.1,10.4,18.8,14.1,106.2,71.5,32.5,26.0,34.5,36.5,23.5,16.5,21,1,65.6
1,43.7,28.5,33.5,14.0,11.8,20.6,15.1,110.5,79.0,34.4,28.0,36.5,37.5,24.5,17.0,23,1,71.8
2,40.1,28.2,33.3,13.9,10.9,19.7,14.1,115.1,83.2,33.4,28.8,37.0,37.3,21.9,16.9,28,1,80.7
3,44.3,29.9,34.0,13.9,11.2,20.9,15.0,104.5,77.8,31.0,26.2,37.0,34.8,23.0,16.6,23,1,72.6
4,41.0,26.8,32.2,14.9,10.6,17.8,14.0,107.5,78.0,36.0,29.0,34.5,35.0,22.0,16.5,23,1,71.0

In [35]:
data.dtypes

biacromial diameter        float64
biiliac diameter           float64
bitrochanteric diameter    float64
elbow diameter             float64
wrist diameter             float64
knee diameter              float64
ankle diameter             float64
shoulder girth             float64
waist girth                float64
bicep girth                float64
forearm girth              float64
knee girth                 float64
calf maximum girth         float64
ankle minimum girth        float64
wrist_min_girth            float64
age                          int64
sex                          int64
weight                     float64
dtype: object

In [36]:
data.isna()

,biacromial diameter,biiliac diameter,bitrochanteric diameter,elbow diameter,wrist diameter,knee diameter,ankle diameter,shoulder girth,waist girth,bicep girth,forearm girth,knee girth,calf maximum girth,ankle minimum girth,wrist_min_girth,age,sex,weight
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
441,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
442,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
443,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
444,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
445,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [37]:
data.isnull().sum()

biacromial diameter        0
biiliac diameter           0
bitrochanteric diameter    0
elbow diameter             0
wrist diameter             0
knee diameter              0
ankle diameter             0
shoulder girth             0
waist girth                0
bicep girth                0
forearm girth              0
knee girth                 0
calf maximum girth         0
ankle minimum girth        0
wrist_min_girth            0
age                        0
sex                        0
weight                     0
dtype: int64

In [38]:
data_weight = data.pop('weight')

data.insert(0,'weight', data_weight)

data.head()

,weight,biacromial diameter,biiliac diameter,bitrochanteric diameter,elbow diameter,wrist diameter,knee diameter,ankle diameter,shoulder girth,waist girth,bicep girth,forearm girth,knee girth,calf maximum girth,ankle minimum girth,wrist_min_girth,age,sex
0,65.6,42.9,26.0,31.5,13.1,10.4,18.8,14.1,106.2,71.5,32.5,26.0,34.5,36.5,23.5,16.5,21,1
1,71.8,43.7,28.5,33.5,14.0,11.8,20.6,15.1,110.5,79.0,34.4,28.0,36.5,37.5,24.5,17.0,23,1
2,80.7,40.1,28.2,33.3,13.9,10.9,19.7,14.1,115.1,83.2,33.4,28.8,37.0,37.3,21.9,16.9,28,1
3,72.6,44.3,29.9,34.0,13.9,11.2,20.9,15.0,104.5,77.8,31.0,26.2,37.0,34.8,23.0,16.6,23,1
4,71.0,41.0,26.8,32.2,14.9,10.6,17.8,14.0,107.5,78.0,36.0,29.0,34.5,35.0,22.0,16.5,23,1

In [39]:
col = ['weight','biacromial diameter','biiliac diameter','bitrochanteric diameter','elbow diameter',
'wrist diameter', 'knee diameter', 'ankle diameter', 'shoulder girth','waist girth','bicep girth','forearm girth',
'knee girth','calf maximum girth','ankle minimum girth','age','sex','wrist_min_girth']

for col_ in col:
    data[col_] = (data[col_] - data[col_].mean())/data[col_].std()

data.head()

,weight,biacromial diameter,biiliac diameter,bitrochanteric diameter,elbow diameter,wrist diameter,knee diameter,ankle diameter,shoulder girth,waist girth,bicep girth,forearm girth,knee girth,calf maximum girth,ankle minimum girth,wrist_min_girth,age,sex
0,-0.252785,1.335451,-0.804699,-0.222173,-0.186075,-0.140547,0.020226,0.214426,-0.189144,-0.497447,0.343131,0.035890,-0.631196,0.160882,0.722286,0.286509,-0.968536,0.998878
1,0.207356,1.597561,0.330903,0.776710,0.476076,1.319641,1.351138,1.010048,0.220316,0.169952,0.790262,0.741039,0.128624,0.506515,1.250038,0.643245,-0.761158,0.998878
2,0.867881,0.418068,0.194631,0.676822,0.402504,0.380949,0.685682,0.214426,0.658343,0.543696,0.554930,1.023098,0.318579,0.437389,-0.122117,0.571898,-0.242715,0.998878
3,0.266729,1.794143,0.966841,1.026431,0.402504,0.693846,1.572956,0.930486,-0.351024,0.063168,-0.009867,0.106405,0.318579,-0.426694,0.458410,0.357856,-0.761158,0.998878
4,0.147983,0.712941,-0.441306,0.127436,1.138227,0.068052,-0.719170,0.134863,-0.065354,0.080966,1.166793,1.093613,-0.631196,-0.357567,-0.069341,0.286509,-0.761158,0.998878

In [46]:
cols = list(np.arange(1,18))
x_data = data[data.columns[cols]]

In [48]:
response_cols = [0]
y_data = data[data.columns[response_cols]]
y_data

       weight
0   -0.252785
1    0.207356
2    0.867881
3    0.266729
4    0.147983
..        ...
441 -0.668396
442 -1.648050
443 -0.868780
444 -0.364109
445 -0.401217

[446 rows x 1 columns]